# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d870a4fa532a2f5ce2fccf60266a9ac4dd7b844e683a98376fa464c482d8256e1f80273153ea44e4cedc03ea92db7aeee5036a4ca38df752f609d128383e9d4

test:
  secret_key_base: 37fab4658d1cc369eef89aac55a1e1c4aac576921d824b09855596b4a1344dd01cb51882f8b023b38e44aa022fd871eb874f28e274d80b4e9196b8cfe674e452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
